apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: stress
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args:
      - apt-get update && apt-get install -y stress-ng && stress-ng --cpu 1 --timeout 60
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "200m"
  restartPolicy: Never

